# Standards: 0.11
---

# 3.6.2 Ensure default deny firewall policy

- name: 3.6.2 - Ensure default deny firewall policy
  iptables:
    chain: {{ item }}
    policy: DROP
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  tags:
    - level-1
    - section-3
    - "3.6.2"
    - scored
